### ISSUE TITLE
有关相位loss的疑问

### ISSUE THREAD

**Issue by yjzxkxdn** [BakerBunker/FreeV#3]
关于解缠绕函数：在APNet里，相位loss对相位差使用负cos函数，但是APNet2换成了线性函数作为解缠绕函数，想了解一下这两者对于训练freeV的区别？
关于瞬时相位损耗（IP_loss）：由于幅度谱对应的最优相位并不唯一，使用瞬时相位损耗是否不利于训练？

**Comment by BakerBunker** [comment]
这篇论文主要是围绕
```python
model_input = (mel_spec @ mel_filter.pinverse()).abs().clamp_min(1e-5)
```
这行代码实验的，所以对相位这方面的尝试不多。

我觉得解缠绕函数的影响应该和apnet和apnet2之间差不多，因为我没有修改相位预测这个分支。
关于IP_loss，APNet的table2有关于这个的消融实验结果，Section 4.C.3也有对这个loss的简要分析:
> The instantaneous phase loss curves of the APNet wo IP and APNet wo P also suggested that the phase difference losses (i.e., LGD and LP TD) had a positive effect on the instantaneous phase loss (i.e., LIP ).

**Comment by yjzxkxdn** [comment]
感谢您的回答
