### ISSUE TITLE
使用预训练模型重建的音频有杂音？（LJspeech除外）

### ISSUE THREAD

**Issue by hildazzz** [BakerBunker/FreeV#4]
感谢大佬分享！
使用FreeV_Model_Logs/freev_g_01000000对音频进行重建时，发现生成的音频有杂音？尝试了好几个样例，都有这样的问题。
请问：
1、出现杂音是为什么呢？但使用LJspeech的数据进行重建就不会出现杂音。
2、我需要一个16k的freev声码器进行测试，是否只能从头训练了？如果是的话，需要修改哪些参数配置呢？

**Comment by BakerBunker** [comment]
1. 杂音应该是正常现象，预训练的模型是用LJSpeech这个单说话人小数据集训练的，所以模型的泛化能力不强是正常现象
2. 是需要从头训练的，改一下config里面的`sampling_rate`就可以了

**Comment by hildazzz** [comment]
> 1. 杂音应该是正常现象，预训练的模型是用LJSpeech这个单说话人小数据集训练的，所以模型的泛化能力不强是正常现象
> 2. 是需要从头训练的，改一下config里面的`sampling_rate`就可以了

多谢及时回复！
